### PR TITLE
Update BNIDA to support the latest Binary Ninja API 3.4.4271 @Diefunction 

### PR DESCRIPTION
**Pull request by Diefunction**
I installed your plugin through Binary Ninja, where I needed to import/export from IDA. However, the plugin did not work for me on version 3.4.4271. Therefore, I made the necessary fixes to enable importing/exporting. I hope the fix is satisfactory.

### CODE REVIEW

**Comment by zznop** [comment]
Please modify this PR so that it only includes code changes. There are a lot of whitespace changes, likely caused by differences in the formatter that you're using, and the formatter that I am using.

**Comment by Diefunction** [comment]
wait i think i did something wrong 😄
when i'm trying to fixing it right now sorry

**Review by Diefunction — COMMENTED** [review]
everything is fine now <3

**Review by Diefunction — COMMENTED** [review]
Works well! I have already tested this commit on Binary Ninja after cloning yours and making only the required code changes.

**Comment by utkonos** [comment]
This appears to fix an exception that the version in Binary Ninja experiences for me. Could this be made into a release to update the main plugin?

**Pull request merged**
